"""
DEPRECATED: Template-based circuit generation has been superseded by LLM-based IR generation.

This file provides minimal stub implementations for backward compatibility only.
All new circuit design should use LLMRouter.generate_circuit_ir() for complete design.

Old usage:
    - TemplatesLoader for loading circuit templates (DEPRECATED)
    - get_loader() for template access (DEPRECATED)

New usage:
    - LLMRouter.generate_circuit_ir() for complete LLM-based design
    - KiCad symbol library via kicad_symbol_library.py for device mapping

Do NOT add new template-based logic. The LLM is the sole engine for circuit generation.
"""

from __future__ import annotations
from typing import Optional, Dict, List, Any


class TemplatesLoader:
    """DEPRECATED: Use LLMRouter.generate_circuit_ir() for LLM-based design.
    
    This stub is kept for backward compatibility with existing services.
    All circuit generation should now be handled by LLM at IR generation time.
    """

    def __init__(self, metadata_dir: Optional[str] = None):
        """Initialize loader (stub for backward compatibility).
        
        Args:
            metadata_dir: Ignored - templates are superseded by LLM
        """
        self.templates: Dict[str, Any] = {}

    def load_templates(self) -> Dict[str, Any]:
        """DEPRECATED: Returns empty dict (templates handled by LLM).
        
        Returns:
            Empty template dictionary
        """
        return {}

    def get_template(self, circuit_type: str) -> Optional[Dict[str, Any]]:
        """DEPRECATED: Returns None (templates handled by LLM).
        
        Args:
            circuit_type: Circuit type (ignored)
            
        Returns:
            None - templates are now generated by LLM
        """
        return None

    def list_templates(self) -> List[str]:
        """DEPRECATED: Returns empty list (templates handled by LLM).
        
        Returns:
            Empty template list
        """
        return []

    def find_template(self, **kwargs) -> Optional[Dict[str, Any]]:
        """DEPRECATED: Returns None (templates handled by LLM).
        
        Args:
            **kwargs: Search criteria (ignored)
            
        Returns:
            None - templates are now generated by LLM
        """
        return None


# Global loader instance (stub for backward compatibility)
_loader_instance: Optional[TemplatesLoader] = None


def get_loader(metadata_dir: Optional[str] = None) -> TemplatesLoader:
    """DEPRECATED: Use LLMRouter.generate_circuit_ir() instead.
    
    Get or create the global TemplatesLoader instance (stub).
    
    Args:
        metadata_dir: Ignored - templates are superseded by LLM
        
    Returns:
        TemplatesLoader stub instance
    """
    global _loader_instance
    if _loader_instance is None:
        _loader_instance = TemplatesLoader(metadata_dir)
    return _loader_instance


# Backward compatibility aliases
__all__ = ["TemplatesLoader", "get_loader"]
